<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>

<!-- 
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCGCCCCCCCCCCCCGCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCGCCCCCGGCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCffffffffLCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:       iCCCCGCCCCCCCGCCCCCCCCCCCCCCCCGCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:       iCCCCCCCCCCCGCCGCCCCCCGCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:       iGCCCCCCCCCCCCGCCCCCCC,       iCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:       iGCCCGC.    1CGCCCCCC1       .CCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:       iCCCCC.      CCCCGCCL        LCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:       iCCCC.       iCCCGCC,       tCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:       iCGL          LCGCC1       :CGCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:       fCf           :CCCC       .CCGCCGCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:       ff      .      tCC:       fCCCGCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:       ;      ,C:     .Ct       iGCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:             .GCf      i       ,GCCCCCCGCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:            .CCCC,             LCCCGCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:           .CGCGCt            tCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:          .CCCGCCG.          ;GCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:          LCCCCCCCi         .CCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCC:         LGCCCCCCCC         LGCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCGCCCCCCCCCCCC:        fCCCCCCCCCC;       iCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCGCCCCCCGCC,       fCCGCCCCCCCCL      ,CCCGCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCGCCCCGC. :tCt,       tCCCCGCGCCCGCC:     CCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCGCCCG.             tCCCCCCCCCCCCCGf    tCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCC.            .LCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCGC:           ;CCCCGCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCfffCCCCGCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCGCCGCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

If you are looking here things to know: 
1. Thanks for looking :)
2. Site went live on 05/01/2012
3. Site was last updated with content on 03/10/2014
4. For most recent code that I am working on please see current project link.
5. Please forgive me I am not a copywriter.
6. And Thanks Agian for looking :)

 -->


<meta charset="<?php bloginfo( 'charset' ); ?>" />
<title><?php wp_title(''); ?></title>
<link rel="apple-touch-icon" href="<?php bloginfo('template_directory'); ?>/images/jw_icon_57.jpg"/>
<link rel="stylesheet" type="text/css" media="all" href="<?php bloginfo('stylesheet_url'); ?>" />
<?php wp_head(); ?>


<meta name="HandheldFriendly" content="True">
<meta name="MobileOptimized" content="320">  
<meta name="viewport" content="width=device-width, initial-scale=1.0, target-densitydpi=160">

<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/global.js"></script>
<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/jquery.timer.js"></script>

<!--[if lt IE 9]>
	<link rel="stylesheet" type="text/css" href="<?php bloginfo('template_directory'); ?>/css/ie8.css" />
<![endif]-->

<!--[if lt IE 8]>
<script type="text/javascript">
$(document).ready(function() {
   alert('This site is optimized for IE8 and above. Some elements and features are not avalible in lower versions.');
});
</script>
<![endif]-->

</head>

<body <?php body_class(); ?>>

<div class="wrapper">
	<div class="center">
		<div class="holder-icon clearfix">
			<a href="<?php echo home_url( '/' ); ?>"><img src="<?php bloginfo('template_directory'); ?>/images/jw_icon.jpg" alt="my-icon" /></a>
		</div>